export const Keys = {
	API_KEYS: "API_KEYS",
	AUTH_TOKEN: "AUTH_TOKEN",
	AUTH_TOKEN_ASYNC: "AUTH_TOKEN_ASYNC",
	PROGRAM_ID: "PROGRAM_ID",
	
	DUMMY_DATA: "DUMMY_DATA",
	
	DEFAULT_ITEMS: "DEFAULT_ITEM",
	DEFAULT_ITEMS_ASYNC: "DEFAULT_ITEM_ASYNC",

	USER_ITEMS: "USER_ITEMS",
	USER_ITEMS_ASYNC: "USER_ITEMS_ASYNC",
	USER_ITEMS_REFRESHER: "USER_ITEMS_REFRESHER",
	
	USER_ITEM_COUNT: "USER_ITEM_COUNT",

	CREATE_USER_ITEM_DATA: "CREATE_USER_ITEM_DATA",
	CREATE_USER_ITEM_ASYNC: "CREATE_USER_ITEM_ASYNC",

	ADD_USER_ITEM_DATA: "ADD_USER_ITEM_DATA",
	ADD_USER_ITEM_ASYNC: "ADD_USER_ITEM_ASYNC",

	HISTORY_DATA: "HISTORY_DATA",
	HISTORY_DATA_ASYNC: "HISTORY_DATA_ASYNC",
	HISTORY_REFRESHER: "HISTORY_REFRESHER",

	SELECTED_ITEM: "SELECTED_ITEM",
	SELECTED_ITEM_RECENT_HISTORY: "SELECTED_ITEM_RECENT_HISTORY",
};
